# Header
menu:
  主页: /
  关于: /about
  tags: /tags/ || fa fa-tags
  分类: /categories
  存档: /archives
  计划: /schedule
  导航: /sitemap.xml
  公共: /404
  评论墙: /评论墙


rss: /atom.xml
nav: right
mobile_nav: right



# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: right
widgets:
- userinfo
- category
- tag
- tagcloud
- archive
- recent_posts
- blogroll

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
- category
#- tagcloud
- archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Background
#background_image: /images/bg.jpeg
background_title: 图片来自网络

# favicon
favicon: /images/default-avatar.jpg

#Userinfo
author: 天天开心
slogan: 我生以悦己，而非为他人所困
#avatar: /images/code-title.png
avatar_title: 图片来自网络

# Article code panel: cloud doorframe mac
highlightPanel: cloud

#Gitment
gitment:
  owner: cai6
  repo: 
  client_id: 
  client_secret: 

# Miscellaneous
google_analytics:
gauges_analytics:
google_site_verification: 
baidu_site_verification: 

# 友情链接
blogroll:
  我的图床: https://image.cai094.top
  Gmail邮箱: mailto:pengcai6@gmail.com
  GitHub: https://github.com/pengcai6


# NeedMoreShare2
# This plugin is a pure javascript sharing lib which is useful in China.
# See: https://github.com/revir/need-more-share2
# Also see: https://github.com/DzmVasileusky/needShareButton
# iconStyle: default | box
# boxForm: horizontal | vertical
# position: top / middle / bottom + Left / Center / Right
# networks: Weibo,Wechat,Douban,QQZone,Twitter,Linkedin,Mailto,Reddit,
#           Delicious,StumbleUpon,Pinterest,Facebook,GooglePlus,Slashdot,
#           Technorati,Posterous,Tumblr,GoogleBookmarks,Newsvine,
#           Evernote,Friendfeed,Vkontakte,Odnoklassniki,Mailru
needmoreshare2:
  enable: true
  postbottom:
    enable: true
    options:
      iconStyle: box
      boxForm: horizontal
      position: bottomCenter
      networks: Weibo,Wechat,Douban,QQZone,Twitter,Facebook

# Easily enable fast Ajax navigation on your website.
# Dependencies: https://github.com/theme-next/theme-next-pjax
pjax: true
inject:
  head:
    - <link rel="stylesheet" href="/css/tag-diy.css"> # 外挂标签
