title: 你也不是我的救赎
subtitle: 
description: 蔡的小破站
keywords: cai
author: cai6
language: zh-CN
timezone: ''
url: https://www.cai094.top
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: butterfly
deploy:
  type: git
  repo: https://github.com/pengcai6/pengcai6.github.io.git
  branch: master
admin:
  username: 3538616223
  password_hash: $2a$10$wI/OsgN/z06.OYUCo5lrkOGhP0UhzmnMs6JVXcivHDHyYMzDeyu2.
  secret: pengcai6@gmail.com
abbrlink:
  alg: crc16
  rep: dec
  drafts: false
  auto_category:
    enable: true
    depth: null
    over_write: false
  auto_title: false
  auto_date: false
  force: false


# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true #开关插件版看板娘
  scriptFrom: local # 默认
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://npm.elemecdn.com/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
    use: live2d-widget-model-z16 # npm-module package name
    # use: wanko # 博客根目录/live2d_models/ 下的目录名
    # use: ./wives/wanko # 相对于博客根目录的路径
    # use: https://npm.elemecdn.com/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
  display:
    position: right #控制看板娘位置
    width: 150 #控制看板娘大小
    height: 300 #控制看板娘大小
  mobile:
    show: true # 手机中是否展示



aplayer:
  cdn: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js
  style_cdn: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css
  meting: true
  meting_cdn: https://cdn.jsdelivr.net/npm/meting/dist/Meting.min.js
  asset_inject: false
backup:
   type: git         # 默认不变
   theme: butterfly      # 备份主题名称
   message: this is my  blog backup  # 提交信息
   repo:
     github: git@github.com:pengcai6/pengcai6.github.io.git,backup
     #gitee: git@gitee.com:Lilbai518/backup-blog.git,master

algolia:
  applicationID: "32J134PA7W" #AppID
  apiKey: "889e81155a79470e446da620e99ca9be" #刚刚新建的API Key
  adminApiKey: "d6b0cf40e68098b44fd7f5b445966dd5" #Admin API Key
  indexName: "hexo" #这个就是Indices填的
  chunkSize: 5000